// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqoGGxlmU1CO09sM5MhNX_aWD4OJyg82o',
    appId: '1:846298274214:web:b0d08dc1908c7295979767',
    messagingSenderId: '846298274214',
    projectId: 'governments-complaints',
    authDomain: 'governments-complaints.firebaseapp.com',
    storageBucket: 'governments-complaints.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT-Kl2pZpcZt8kslQCBjsZ5hrspfAjWYA',
    appId: '1:1811023836:android:3f24e05631828817dab119',
    messagingSenderId: '1811023836',
    projectId: 'comolaints-c85ed',
    storageBucket: 'comolaints-c85ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLYSoL8gR6WNvor1jz9bbJcwOGNDhgYOc',
    appId: '1:1811023836:ios:f7d5ab90b5be5d25dab119',
    messagingSenderId: '1811023836',
    projectId: 'comolaints-c85ed',
    storageBucket: 'comolaints-c85ed.firebasestorage.app',
    iosBundleId: 'com.example.governmentsComplaints',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiV5fx3BIzW1QTrOm9CWZBbYLRbz0XmBA',
    appId: '1:846298274214:ios:4641252f57ccdd56979767',
    messagingSenderId: '846298274214',
    projectId: 'governments-complaints',
    storageBucket: 'governments-complaints.firebasestorage.app',
    iosBundleId: 'com.example.governmentsComplaints',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqoGGxlmU1CO09sM5MhNX_aWD4OJyg82o',
    appId: '1:846298274214:web:aac4c98b6aec46ec979767',
    messagingSenderId: '846298274214',
    projectId: 'governments-complaints',
    authDomain: 'governments-complaints.firebaseapp.com',
    storageBucket: 'governments-complaints.firebasestorage.app',
  );

}